from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from app.database import get_db
from app.models.user import User
from app.models.channel import Channel
from app.models.script import Script
from app.utils.auth_utils import get_current_user
from app.intelligence.script_generator import ScriptGenerator
from app.schemas.script import ScriptCreateRequest, ScriptResponse
from app.deps import check_script_monthly_limit, check_token_budget, rate_limit
from typing import List
import logging

logger = logging.getLogger(__name__)

router = APIRouter()
generator = ScriptGenerator()

@router.post("/generate", response_model=ScriptResponse, status_code=201, tags=["scripts"])
def generate_script(
    request: ScriptCreateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
    _plan: None = Depends(check_script_monthly_limit),
    _budget: None = Depends(check_token_budget),
    _rate: None = Depends(rate_limit("script_generate")),
):
    """
    Generates a complete script in 3 steps:
    1. Title suggestions
    2. Hook generation
    3. Full script
    
    - **topic**: The video topic/idea
    - **channel_id**: Optional - for personalized script based on channel style
    - **target_duration_minutes**: Target video length (default 10)
    - **format_type**: Video format (educational, story, list, review)
    
    This is a blocking call that takes 15-30 seconds to complete.
    """
    channel = None
    if request.channel_id:
        channel = db.query(Channel).filter(
            Channel.id == request.channel_id,
            Channel.user_id == current_user.id
        ).first()

    # Create script record
    script = Script(
        user_id=current_user.id,
        channel_id=request.channel_id,
        topic=request.topic,
        target_duration_minutes=request.target_duration_minutes,
        format_type=request.format_type,
        generation_status="generating"
    )
    db.add(script)
    db.commit()

    try:
        titles = generator.generate_titles(request.topic, channel, user_id=str(current_user.id)) if channel else []
        selected_title = titles[0]["title"] if titles else request.topic
        hook = generator.generate_hook(request.topic, channel, selected_title, user_id=str(current_user.id)) if channel else ""
        full = generator.generate_full_script(
            topic=request.topic,
            title=selected_title,
            hook=hook,
            channel=channel,
            target_duration_minutes=request.target_duration_minutes,
            format_type=request.format_type,
            user_id=str(current_user.id),
        )

        script.title_suggestions = [t["title"] if isinstance(t, dict) else str(t) for t in titles]
        script.hook = hook
        script.full_script = full.get("full_script", "")
        script.generation_status = "done"
        db.commit()
        db.refresh(script)
        logger.info(f"Script generated successfully: {script.id}")
        return script

    except Exception as e:
        logger.error(f"Script generation failed: {e}")
        script.generation_status = "failed"
        db.commit()
        raise HTTPException(status_code=500, detail=f"Script generation failed: {str(e)}")

@router.get("/", response_model=List[ScriptResponse], tags=["scripts"])
def list_scripts(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    List all scripts generated by the current user, newest first.
    """
    return db.query(Script).filter(Script.user_id == current_user.id).order_by(Script.created_at.desc()).all()

@router.get("/{script_id}", response_model=ScriptResponse, tags=["scripts"])
def get_script(
    script_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Get a specific script by ID.
    
    - **script_id**: UUID of the script
    """
    script = db.query(Script).filter(
        Script.id == script_id,
        Script.user_id == current_user.id
    ).first()
    if not script:
        raise HTTPException(status_code=404, detail="Script not found")
    return script

@router.delete("/{script_id}", status_code=204, tags=["scripts"])
def delete_script(
    script_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Delete a script.
    
    - **script_id**: UUID of the script to delete
    """
    script = db.query(Script).filter(
        Script.id == script_id,
        Script.user_id == current_user.id
    ).first()
    if not script:
        raise HTTPException(status_code=404, detail="Script not found")
    db.delete(script)
    db.commit()
    logger.info(f"Script deleted: {script_id}")